Main 페이지 레이아웃 구현중
Jeong-minji/PixelDemo pull request #2
Opened 2022-01-04 10:12 UTC by Jeong-minji

## :: 최근 작업 주제 
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 

<br />

## :: 구현 사항 설명

## :: 구현 화면

## :: 기타 특이사항

2022-01-11 08:25 UTC, heejinlee07 requested changes
고생하셨습니다 :) 
이번에는 로또도 추가로 pr 해주실거예요!
기다려주세요

2022-01-11 08:25 UTC, heejinlee07 commented on api/Entity/index.ts
> +export interface Url {
P1 : 여기는 `API` 관련된 내용만 있는 API 디렉토리이기 때문에 type 관련 파일은 별도의 디렉토리에 지정하셔서 사용하도록 합니다. 일전에 말씀 드렸는데요 types 또는 interfaces 같은 디렉토리에 타입에 관련된 파일을 저장하면 됩니다.

디렉토리 구조 참조 : https://github.com/vercel/next.js/tree/canary/examples/with-typescript

2022-01-11 08:25 UTC, heejinlee07 commented on api/routeUri.ts
> +export const login = "/auth/local";
P1 : 이 파일 이름이 routeUr`i`인데, URI와 URL은 다릅니다. 이 경우는 URL이 맞습니다. URI와 URL의 차이점은 아래를 보고 공부하세요

https://www.geeksforgeeks.org/difference-between-url-and-uri/

2022-01-11 08:25 UTC, heejinlee07 commented on components/common/Nav/Nav.tsx
> +    // localStorage.removeItem("token");
P1 : 풀리퀘시 주석은 남기지 않습니다

2022-01-11 08:25 UTC, heejinlee07 commented on components/common/Nav/Nav.tsx
> +      {TOKEN ? (
P1 : 로그아웃 상태에서는 현재 컴포넌트를 부르지 않기 때문에 TOKEN 값에 따라 버튼을 분기하는 것이 아니라 로그아웃 버튼만 있어야 하고, TOKEN이 없을 때는 로그인 페이지로 이동하는 방식으로 변경해주세요 아마 그러면 말씀하신 에러는 사라질 거예요

2022-01-11 08:25 UTC, heejinlee07 commented on pages/index.tsx
> +          (nowPage - 1) * 5 + 1
P2 : 이런 숫자들은 매직넘버로 빼주세요

2022-01-11 08:41 UTC, Jeong-minji commented on components/common/Nav/Nav.tsx
> +    // localStorage.removeItem("token");
주석 풀었어야 하는데.. 까먹었네요ㅠ 꼭 한번씩 더 확인하겠습니다!

2022-01-11 08:43 UTC, Jeong-minji commented on components/common/Nav/Nav.tsx
> +      {TOKEN ? (
생각해보니까 어차피 로그인 버튼이 있을 필요가 없네요...
제가 왜 그 생각을 못했을까요
명쾌한 해답 감사합니다! 덕분에 에러가 사라졌습니다 😊

2022-01-11 08:43 UTC, Jeong-minji commented on pages/index.tsx
> +          (nowPage - 1) * 5 + 1
해당 부분도 반영하였습니다!

2022-01-11 08:44 UTC, Jeong-minji commented on api/routeUri.ts
> +export const login = "/auth/local";
URL로 할지 URI로 할지 고민하다가 URI를 선택했는데... 반대로 알고있었군요 부끄럽습니다 ㅠ 더 열심히 공부하겠습니다

2022-01-11 08:45 UTC, Jeong-minji commented on api/Entity/index.ts
> +export interface Url {
디렉토리 구조 구축하는게 제 기준에서 제일 헷갈리는거 같네요!
이런 공식 깃헙과 문서 보면서 표준적인 구조를 익히도록 노력하겠습니다
해당 부분도 interfaces 폴더 따로 만들어서 반영하였습니다

2022-01-11 09:56 UTC, Lissu-FE requested changes
고생하셨습니다!

- 토큰값을 다 지운 상태로 메인 페이지 접근시 로그인페이지로 튕겨내지 않습니다.
- 로그아웃 버튼 클릭시 로그인을 하려고 하면 안됩니다.

이 두가지도 같이 확인해주세요!

2022-01-11 09:56 UTC, Lissu-FE commented on pages/sign-in.tsx
> +        window.location.replace("/");
❓ router에서 location으로 변경한 이유가 있나요??

2022-01-11 09:56 UTC, Lissu-FE commented on pages/index.tsx
> +    </>
❓ setNowPage를 직접 전달하지 않고 getIndex로 변경해서 전달한 이유가 궁금합니다!

2022-01-11 09:56 UTC, Lissu-FE commented on components/layout/Main/Store.tsx
> +import * as Entity from "../../../interfaces/Entity/index";
P3: *로 다 가져오는건 성능에 좋지 않아요! 다 사용하지 않는다면 필요한것만 가져오는것이 어떨까요?

2022-01-11 09:56 UTC, Lissu-FE commented on components/layout/Main/Content.tsx
> +          <AuthorImage img={userinfo.profile?.url}></AuthorImage>
P4: children이 없다면 <AuthorImage img={userinfo.profile?.url} /> 으로 사용하는건 어떨까요?!

2022-01-11 09:56 UTC, Lissu-FE commented on components/common/Nav/Nav.tsx
> +  BtnLogin,
Btn Login이 사용되지 않고 있어요!

2022-01-11 09:56 UTC, Lissu-FE commented on styles/Main/MainStyle.ts
> +export const Wrapper = styled.div``;
❓ 아무 스타일 적인 내용이 없는데 직접 div로 쓰지 않고 style파일로 뺀 이유가 있나요??

2022-01-11 09:56 UTC, Lissu-FE commented on styles/Main/NavStyle.ts
> +export const BtnLogout = styled(Button)``;
main style과 같은 질문!

2022-01-11 09:56 UTC, Lissu-FE commented on styles/Main/ContentStyle.ts
> +`;
❓ img 태그가 아닌 div를 사용해서 background 이미지로 사용하는 이유가 있나요???

2022-01-11 09:56 UTC, Lissu-FE commented on components/layout/Main/Pagenation.tsx
> +        disabled={pageGroup === 4 ? true : false}
❓ disabled에 따른 변화가 없어요! 어떤걸 의도한건지 궁금해요.

2022-01-11 09:56 UTC, Lissu-FE commented on components/layout/Main/Pagenation.tsx
> +  const [index, setIndex] = useState<number>(1);
❓ 이곳의 인덱스와 부모의 인덱스가 항상 같은 값을 가지는것같아요. 내려받지 않고 따로 useState해서 사용한 이유가 있나요??

2022-01-11 09:56 UTC, Lissu-FE commented on components/layout/Main/Pagenation.tsx
> +        onClick={handleDirection}
맨 뒷페이지로 간 다음 앞으로 가는 버튼을 계속 누르면 에러가 납니다. 확인한번 부탁드려요

2022-01-12 03:56 UTC, Jeong-minji commented on pages/sign-in.tsx
> +        window.location.replace("/");
sign-in 페이지에서 로그인 성공 후 메인 페이지로 넘어왔을 때, nav와 banner에서 바로 유저데이터를 get하려면 토큰 값이 필요한데, router로 구현했을 시에 localStorage의 토큰값을 반영을 못해줘서 location으로 변경하게 되었습니다.
혹시 더 좋은 방법이 있다면 알려주세요!

2022-01-12 03:57 UTC, Jeong-minji commented on pages/index.tsx
> +    </>
setNowPage를 직접 전달해주는 방식으로 변경하였습니다!
괜히 복잡하게 생각했던 것 같습니다.
이로 인해서 파생된 다른 복잡한 코드들도 해결되었습니다 😀

2022-01-12 03:57 UTC, Jeong-minji commented on components/layout/Main/Store.tsx
> +import * as Entity from "../../../interfaces/Entity/index";
넵! 이부분도 반영하여 수정 완료 하였습니다.

2022-01-12 03:58 UTC, Jeong-minji commented on components/layout/Main/Content.tsx
> +          <AuthorImage img={userinfo.profile?.url}></AuthorImage>
아래 말씀하신 것처럼 img 태그를 사용하면 되는데 div를 사용해서 저렇게 놔둔 것 같습니다...
이부분도 img 태그로 변경하였고 self-closing 하도록 변경하였습니다.

2022-01-12 03:58 UTC, Jeong-minji commented on components/common/Nav/Nav.tsx
> +  BtnLogin,
해당 부분 삭제하였습니다!

2022-01-12 03:59 UTC, Jeong-minji commented on styles/Main/MainStyle.ts
> +export const Wrapper = styled.div``;
이부분은 삭제되는게 맞습니다. 미처 확인하지 못했네요 주의하겠습니다 😅

2022-01-12 04:00 UTC, Jeong-minji commented on styles/Main/NavStyle.ts
> +export const BtnLogout = styled(Button)``;
두 버튼의 스타일이 중복되는 속성이 많아서 Btn이라는 하나의 변수에 스타일을 담고, 이를 각 버튼에 또 적용해주기 위해 나눠놓았던 것인데, 어제 피드백 받으면서 로그인 버튼을 삭제하게 되어 의미가 없어진 코드입니다.
해당부분도 수정하였습니다!

2022-01-12 04:00 UTC, Jeong-minji commented on styles/Main/ContentStyle.ts
> +`;
제가 왜그랬을까요? ㅠ 시멘틱 태그 준수하겠습니다..!

2022-01-12 04:02 UTC, Jeong-minji commented on components/layout/Main/Pagenation.tsx
> +        disabled={pageGroup === 4 ? true : false}
페이지네이션 레이아웃 변경되기 전에  총 20쪽 까지 있는 것으로 가정하고 구현했어서 그 때 마지막 부분 핸들링 해주려고 해놓았던 부분입니다. 변경하면서 저부분도 수정했어야 되는데 미처 신경을 못썼네요
이번 레이아웃에 맞는 핸들링으로 수정 완료 하였습니다!

2022-01-12 05:07 UTC, Jeong-minji commented on components/layout/Main/Pagenation.tsx
> +  const [index, setIndex] = useState<number>(1);
처음에 부모의 인덱스 값과 Pagenation 컴포넌트의 인덱스 값이 같을 때를 조건으로 하여, 같으면 focus 스타일을 내려주어 현재 페이지를 표시하는 방식을 구현하려고 이렇게 코드를 작성했었는데, 
이부분도 setNowPage를 직접적으로 내려주면서 자동으로 해결되었습니다!

2022-01-12 05:09 UTC, Jeong-minji commented on components/layout/Main/Pagenation.tsx
> +        onClick={handleDirection}
이 부분 살펴보았더니, 정확하지는 않지만 천천히 넘길 때는 괜찮은데 마우스 클릭을 빨리 하니까 id값을 가져오지 못하면서 이러한 문제가 발생하는 것 같습니다. 마지막 페이지 limit 정해서 못넘어가게 막아두고, id값이 가져와졌을 때만 setState 할 수 있도록 조건 걸어두는 방식으로 변경해서 우선 에러가 없는데, 혹시 또 에러가 나타나면 알려주세요!

2022-01-12 05:11 UTC, Jeong-minji commented on pages/sign-in.tsx
> +        window.location.replace("/");
토큰값 지웠을 때 메인 접근 시 로그인 페이지로 보내기 및 토큰 있을 때 로그인 페이지 접근 시 홈으로 보내기도 반영하였습니다. 그리고 별도로 말씀해주신 createdAt 내림차순과 hover 이미지 없을 때 변경 안되게 하는 것도 반영 완료하였습니다!
자세한 리뷰 감사합니다 😍

2022-01-12 05:33 UTC, Lissu-FE approved these changes
LGTM😍

2022-01-12 05:35 UTC, heejinlee07 approved these changes
LGTM 머지해주세요!

2022-01-12 06:10 UTC, merged